import { Character } from './CharacterData';

export const STARTING_CAST: Character[] = [
  {
    id: 'rosie',
    name: 'Rosie',
    species: 'rabbit',
    personality: {
      extroversion: 65,
      agreeableness: 90,
      confidence: 55,
      humor: 85,
      loyalty: 70,
    },
    colorPalette: {
      primary: 'pink',
      secondary: 'white',
      accent: 'red',
    },
    catchphrase: "Lettuce be honest, you're un-bunny-lievable!",
    backstory:
      'Rosie grew up in a cozy countryside burrow surrounded by wildflower gardens. She spent her youth writing love letters she never sent and perfecting her carrot cake recipe. She joined Lub Island hoping to finally find someone who appreciates a good pun as much as a good sunrise.',
    romanceInterest: 'romantic',
    preferredTraits: ['humor', 'kindness', 'creativity'],
    dislikedTraits: ['arrogance', 'cynicism', 'laziness'],
    activityPreference: 'early_bird',
    preferredZone: 'Garden',
    relationshipToPlayer: 0,
    currentPartner: null,
    isEliminated: false,
    dayJoined: 1,
  },
  {
    id: 'blaze',
    name: 'Blaze',
    species: 'fox',
    personality: {
      extroversion: 80,
      agreeableness: 30,
      confidence: 95,
      humor: 60,
      loyalty: 40,
    },
    colorPalette: {
      primary: 'orange',
      secondary: 'dark-red',
      accent: 'gold',
    },
    catchphrase: "Keep up or step aside -- I don't do second place.",
    backstory:
      'Blaze clawed his way out of a rough den on the wrong side of the forest. Street-smart and self-made, he learned early that charm opens more doors than honesty. He sees Lub Island as the ultimate arena where only the sharpest fox walks away with the prize.',
    romanceInterest: 'competitive',
    preferredTraits: ['ambition', 'confidence', 'wit'],
    dislikedTraits: ['weakness', 'indecisiveness', 'clinginess'],
    activityPreference: 'balanced',
    preferredZone: 'Challenge Arena',
    relationshipToPlayer: 0,
    currentPartner: null,
    isEliminated: false,
    dayJoined: 1,
  },
  {
    id: 'pudge',
    name: 'Pudge',
    species: 'bear',
    personality: {
      extroversion: 25,
      agreeableness: 92,
      confidence: 40,
      humor: 55,
      loyalty: 95,
    },
    colorPalette: {
      primary: 'brown',
      secondary: 'cream',
      accent: 'honey',
    },
    catchphrase: "I, um... I made you something. I hope it's okay.",
    backstory:
      'Pudge spent most of his life in a quiet mountain lodge, learning recipes from his grandmother and tending a small herb garden. He has never been on a date and blushes at the mere thought of romance. His friends signed him up for Lub Island behind his back, convinced that his warm heart deserves to be shared.',
    romanceInterest: 'either',
    preferredTraits: ['gentleness', 'patience', 'honesty'],
    dislikedTraits: ['aggression', 'showboating', 'dishonesty'],
    activityPreference: 'early_bird',
    preferredZone: 'Villa',
    relationshipToPlayer: 0,
    currentPartner: null,
    isEliminated: false,
    dayJoined: 1,
  },
  {
    id: 'kiki',
    name: 'Kiki',
    species: 'cat',
    personality: {
      extroversion: 50,
      agreeableness: 50,
      confidence: 85,
      humor: 50,
      loyalty: 55,
    },
    colorPalette: {
      primary: 'black',
      secondary: 'purple',
      accent: 'silver',
    },
    catchphrase: 'Curiosity never killed this cat -- it made her interesting.',
    backstory:
      'Kiki drifted between cities as a street performer and part-time tarot reader, collecting secrets the way others collect stamps. Nobody quite knows where she came from, and she likes it that way. She arrived on Lub Island not to find love but to see if anyone could hold her attention long enough to matter.',
    romanceInterest: 'romantic',
    preferredTraits: ['mystery', 'intelligence', 'independence'],
    dislikedTraits: ['predictability', 'neediness', 'loud-mouthing'],
    activityPreference: 'night_owl',
    preferredZone: 'Beach',
    relationshipToPlayer: 0,
    currentPartner: null,
    isEliminated: false,
    dayJoined: 1,
  },
  {
    id: 'sprocket',
    name: 'Sprocket',
    species: 'penguin',
    personality: {
      extroversion: 90,
      agreeableness: 70,
      confidence: 30,
      humor: 95,
      loyalty: 65,
    },
    colorPalette: {
      primary: 'black',
      secondary: 'white',
      accent: 'yellow',
    },
    catchphrase: "If you're not laughing, I'm not trying hard enough!",
    backstory:
      'Sprocket was always the loudest chick in the colony, cracking jokes to mask the fact that he never quite felt like he fit in. Behind the constant laughter is a penguin terrified of silence and what people might think if they saw the real him. He came to Lub Island hoping a true friend might finally see past the act.',
    romanceInterest: 'friendship',
    preferredTraits: ['humor', 'acceptance', 'warmth'],
    dislikedTraits: ['judgmental', 'seriousness', 'cruelty'],
    activityPreference: 'balanced',
    preferredZone: 'Beach',
    relationshipToPlayer: 0,
    currentPartner: null,
    isEliminated: false,
    dayJoined: 1,
  },
  {
    id: 'lily',
    name: 'Lily',
    species: 'frog',
    personality: {
      extroversion: 30,
      agreeableness: 65,
      confidence: 35,
      humor: 55,
      loyalty: 90,
    },
    colorPalette: {
      primary: 'green',
      secondary: 'lime',
      accent: 'pink',
    },
    catchphrase: 'The forest has all the answers... if you listen.',
    backstory:
      'Lily grew up on a mossy lily pad at the edge of an ancient rainforest, happiest when listening to the chorus of cicadas at dusk. She keeps a journal of every wildflower she has ever found and speaks to plants as though they can hear her. She came to Lub Island because a fortune-teller told her the next chapter of her story begins on an island far from home.',
    romanceInterest: 'either',
    preferredTraits: ['nature-loving', 'calmness', 'loyalty'],
    dislikedTraits: ['recklessness', 'materialism', 'loudness'],
    activityPreference: 'early_bird',
    preferredZone: 'Jungle',
    relationshipToPlayer: 0,
    currentPartner: null,
    isEliminated: false,
    dayJoined: 1,
  },
];

export const PLAYER_CHARACTER: Character = {
  id: 'player',
  name: 'Player',
  species: 'dog',
  personality: {
    extroversion: 50,
    agreeableness: 50,
    confidence: 50,
    humor: 50,
    loyalty: 50,
  },
  colorPalette: {
    primary: 'golden',
    secondary: 'white',
    accent: 'blue',
  },
  catchphrase: '',
  backstory: 'A bright-eyed dog ready to make friends and find love on Lub Island.',
  romanceInterest: 'either',
  preferredTraits: [],
  dislikedTraits: [],
  activityPreference: 'balanced',
  preferredZone: 'Villa',
  relationshipToPlayer: 0,
  currentPartner: null,
  isEliminated: false,
  dayJoined: 1,
};
